language: go
go:
  - 1.15.5
  - 1.15.6
  - release
os:
  - linux
dist: trusty
sudo: false
install: true
env:
  - GO111MODULE=on
script:
  go test ./tests/...

  deploy:
  provider: releases
  skip_cleanup: true