language: go
go:
  - 1.15.6
os: linux
dist: xenial
script:
  - go get github.com/serkanalgur/phpfuncs
  - go test -v ./tests/...
  - go test -coverprofile=coverage.txt -covermode=atomic ./tests/...
after_success:
  - bash <(curl -s https://codecov.io/bash)
