language: go
go:
  - release
install:
  - export GOPATH=$HOME/go
  - go get -t -v ./...
os: linux
dis: xenial
env:
  - GO111MODULE=on
script:
  - go test -coverprofile=coverage.txt -covermode=atomic
  - go test $GOPATH/tests/...
after_success:
  - bash <(curl -s https://codecov.io/bash)
